import Foundation

/// Application version information
/// For release builds, VersionInfo is generated by scripts/set-version.sh
/// For development builds, defaults are used
enum AppVersion {
    /// The semantic version number (e.g., "1.0.0")
    static var version: String {
        VersionInfo.version
    }

    /// The git commit hash
    static var gitCommit: String {
        VersionInfo.gitCommit
    }

    /// The build date
    static var buildDate: String {
        VersionInfo.buildDate
    }

    /// Full version string for display
    static var fullVersion: String {
        if version == "dev" {
            return "Development Build"
        }
        return "v\(version)"
    }

    /// Detailed version string including commit info
    static var detailedVersion: String {
        if version == "dev" {
            return "Development Build"
        }
        return "v\(version) (\(String(gitCommit.prefix(7))))"
    }
}
